// <auto-generated />
using LocalBusiness.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalBusiness.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230120171827_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LocalBusiness.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Review")
                        .HasColumnType("int");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            Description = "Chinese Restaurant",
                            Name = "Panda Fast",
                            Review = 3
                        },
                        new
                        {
                            BusinessId = 2,
                            Description = "Supermarket",
                            Name = "Walmarket",
                            Review = 4
                        },
                        new
                        {
                            BusinessId = 3,
                            Description = "Mexican Restaurant",
                            Name = "Tortilla Bell",
                            Review = 3
                        },
                        new
                        {
                            BusinessId = 4,
                            Description = "Fast food chicken restaurant",
                            Name = "Girl-Fil-A",
                            Review = 4
                        },
                        new
                        {
                            BusinessId = 5,
                            Description = "Coffee shop",
                            Name = "Sunbucks",
                            Review = 2
                        },
                        new
                        {
                            BusinessId = 6,
                            Description = "Coffee/Donut shop",
                            Name = "Dippin Donuts",
                            Review = 2
                        },
                        new
                        {
                            BusinessId = 8,
                            Description = "Wine store",
                            Name = "Crushed Grapes",
                            Review = 1
                        },
                        new
                        {
                            BusinessId = 9,
                            Description = "American restaurant",
                            Name = "Apple A Plus",
                            Review = 5
                        },
                        new
                        {
                            BusinessId = 7,
                            Description = "Coffee shop",
                            Name = "Moonbucks",
                            Review = 5
                        },
                        new
                        {
                            BusinessId = 10,
                            Description = "American diner",
                            Name = "IJump",
                            Review = 3
                        },
                        new
                        {
                            BusinessId = 11,
                            Description = "Home Improvement Company",
                            Name = "House Depot",
                            Review = 1
                        },
                        new
                        {
                            BusinessId = 12,
                            Description = "Furniture Company",
                            Name = "Bobithy Furniture",
                            Review = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
